//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopOrchestra.Kinect.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaptopOrchestra.Kinect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera: HIDE.
        /// </summary>
        internal static string CameraStateHide {
            get {
                return ResourceManager.GetString("CameraStateHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera: SHOW.
        /// </summary>
        internal static string CameraStateShow {
            get {
                return ResourceManager.GetString("CameraStateShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KiCASS-desktop.
        /// </summary>
        internal static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ready Kinect found!.
        /// </summary>
        internal static string NoSensorStatusText {
            get {
                return ResourceManager.GetString("NoSensorStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation: MIRRORED.
        /// </summary>
        internal static string OrientStateMirror {
            get {
                return ResourceManager.GetString("OrientStateMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation: TRUE.
        /// </summary>
        internal static string OrientStateTrue {
            get {
                return ResourceManager.GetString("OrientStateTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string RunningStatusText {
            get {
                return ResourceManager.GetString("RunningStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect not available!.
        /// </summary>
        internal static string SensorNotAvailableStatusText {
            get {
                return ResourceManager.GetString("SensorNotAvailableStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRACKING.
        /// </summary>
        internal static string TrackStateActive {
            get {
                return ResourceManager.GetString("TrackStateActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOADING.
        /// </summary>
        internal static string TrackStateLoading {
            get {
                return ResourceManager.GetString("TrackStateLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STANDBY.
        /// </summary>
        internal static string TrackStateStandby {
            get {
                return ResourceManager.GetString("TrackStateStandby", resourceCulture);
            }
        }
    }
}
